### ISSUE TITLE
Moz Hacks Fullscreen API post lacks MS prefixes, so won't work in IE11+

### ISSUE THREAD

**Issue by dstorey** [dstorey/stale#1]
URL: https://hacks.mozilla.org/2012/01/using-the-fullscreen-api-in-web-browsers/

Issues:
- No ms prefix (should be used with latest syntax)
- WebKit uses older syntax (won't break anything, but may be nice to update). Note: WebKit still requires old CSS syntax (with hyphen), IE doesn’t
- Support info out of date (less of an issue but may as well be updated with the rest)

The code is stored in a GitHub repo, so we can issue a pull request, but the text will have to be updated by the author

Contact: 

Github: @robnyman, 
Twitter: @robertnyman (author)

**Comment by dstorey** [comment]
Also reposted here: http://css.dzone.com/articles/pragmatic-introduction-html5

**Comment by robnyman** [comment]
I'd be happy to update the text in the article to mention IE11 support if you issue pull requests for the code! The reposting is done automatically by them, though, so I don't have clear access to that content.

**Comment by dstorey** [comment]
@robnyman thanks! I’ve issued a pull request. It should work as expected.

**Comment by robnyman** [comment]
Pull request accepted, article and corresponding gists updated!
- Robert

**Comment by dstorey** [comment]
Thanks! Closing this bug. Just one slight nitpick. The text says “Note here that W3C has decided to call it exitFullscreen, but in all existing web browser implementations it’s about cancelling the state.” It should probably be updated to “…in all existing web browser implementations except IE…” Actually scratch that as WebKit supports both syntaxes, so I believe it is only Firefox that requires the old syntax.

**Comment by robnyman** [comment]
Yeah, that's a fair point. I updated the post to the vague "Note here that
there have been differences in this naming, and in some implementations
it's about exiting the state, in others cancelling it."
- Robert
