### ISSUE TITLE
ColorZilla: gradient generator adds redundant -ms- prefix

### ISSUE THREAD

**Issue by dstorey** [dstorey/stale#11]
URL: http://www.colorzilla.com/gradient-editor/

Issue:

IE10 release preview added the final unprefixed syntax of CSS Gradients. No final release came out requiring the -ms- prefix with older syntax. Thus the -ms- prefix is added redundant code that can be removed.

Fix:

Remove the -ms- prefixed background declaration from the generated code.

Contact:

Twitter: @colorzilla

**Comment by ghost** [comment]
The generated comments also make it look like no browser supports the current standard syntax (which [hasn't been the case for quite a while](http://caniuse.com/#feat=css-gradients)). I've tweeted at them a few times during the past year, nothing changed.

**Comment by dstorey** [comment]
Contacted by the feedback form on his personal site. Hopefully it lands in the correct place.

**Comment by dstorey** [comment]
This is now fixed (for regular output). Thanks @thebabydino!
