### ISSUE TITLE
HTML5Rocks “Let Your Content Do the Talking: Fullscreen API” outdated syntax

### ISSUE THREAD

**Issue by dstorey** [dstorey/stale#2]
URL: http://updates.html5rocks.com/2011/10/Let-Your-Content-Do-the-Talking-Fullscreen-API

Issues:
- Lacks ms prefix for IE11+
- Lacks unprefixed CSS with updated syntax (without hyphen in `:fullscreen`.) IE supports the new syntax for this, WebKit supports the latest syntax for JS but not CSS (still requires hyphen)
- May as well update support info to mention it is also in IE11+

Contact:

Github & Twitter: @ebidel (Author)

**Comment by ebidel** [comment]
We don't actively update the mini h5r posts. Paul's article at http://www.html5rocks.com/en/mobile/fullscreen/ is a better candidate to keep up to date.

**Comment by dstorey** [comment]
Unfortunately this post is high up in Google search results (6th place), so it will show up a bunch when people are searching how to use the Fullscreen API. 

If you don’t want to update it, it would be nice to add a banner saying it is out of date or something.

**Comment by dstorey** [comment]
@ebidel I can fix it myself if you can point out where it is in the GitHub repo. I can’t seem to find the blog posts.

**Comment by ebidel** [comment]
The update posts are entered in a raw CMS. Here's the markdown:
http://jsbin.com/sutej/1/edit

Thanks!

**Comment by patrickkettner** [comment]
[Updated and ready for review](http://jsbin.com/sutej/2/edit)

**Comment by ebidel** [comment]
Thanks!. David, do you want to look this over? I'm not up to snuff on the
latest and greatest, but it looks like the changes were small.

**Comment by dstorey** [comment]
No, it’s incorrect. You can’t chain css selectors with prefixes, and uses the old syntax for IE11 instead of the new syntax. I’ll create an alternative update now…

**Comment by patrickkettner** [comment]
wompwomp - [updated](http://jsbin.com/sutej/3/edit)

**Comment by dstorey** [comment]
This should be correct http://jsbin.com/sutej/4/edit :+1: 
- Changed Opera comment to “standard” as Opera now uses the Webkit prefix
- Added ms prefixes the requestFullscreen and exitFullscreen
- Added -ms- prefix to :fullscreen and added unprefixed version
- Changed note after the exiting fullscreen section to mention cancelFullScreen rather than cancelFullscreen as the old syntax uses uppercase S
- Updated browser compat to mention IE11

**Comment by dstorey** [comment]
@patrickkettner thanks for the update, much appreciated. That still has a couple of issues: msRequestFullScreen should be msRequestFullscreen, there is a second block of CSS rules that need prefixes and new syntax, and there is a stray } in the note. Let’s go with the update I did above.

@ebidel I think my update above should be good. The demo linked from appspot should be updated with the changes too if possible. It looks like that is on GitHub, so I can probably fit it myself. I noticed the iframe full screen isn't working in Safari either.

**Comment by ebidel** [comment]
Thanks fellas. Updated and gave you both credit:

http://updates.html5rocks.com/2011/10/Let-Your-Content-Do-the-Talking-Fullscreen-API

The demo is here if you want to help with a PR:
https://github.com/ebidel/html5demos/blob/master/html5-demos.appspot.com/static/fullscreen.html

**Comment by dstorey** [comment]
Thanks. Resolved. Verified.
