### ISSUE TITLE
the-haystack Flexbox articles are out of date. Need revised disclaimer

### ISSUE THREAD

**Issue by dstorey** [dstorey/stale#20]
URL: http://www.the-haystack.com/2010/01/23/css3-flexbox-part-1/ and http://www.the-haystack.com/2012/01/04/learn-you-a-flexbox/

Issues:

The articles include a disclaimer stating things have changed. Would be great to add another disclaimer (or change the older ones) to point to the latest syntax: https://github.com/h5bp/lazyweb-requests/issues/124#issuecomment-27273696

Contact: @stephenhay (GitHub)

**Comment by stephenhay** [comment]
Done. http://www.the-haystack.com/2012/01/04/learn-you-a-flexbox/ and http://www.the-haystack.com/2010/01/23/css3-flexbox-part-1/ now have a note at the top. Other notes have been `<del>`eted.

**Comment by dstorey** [comment]
@stephenhay Thanks! Closing. Verified.
