### ISSUE TITLE
Tutsplus “An Introduction to the CSS Flexbox Module” needs updating or a disclaimer

### ISSUE THREAD

**Issue by dstorey** [dstorey/stale#23]
URL: http://code.tutsplus.com/tutorials/an-introduction-to-css-flexbox--net-25655

Issue:

Flexbox syntax has changed since the tutorial was written. As the post has high search engine ranking, or is otherwise easy to find, it would be great to either add a disclaimer (see https://github.com/h5bp/lazyweb-requests/issues/124#issuecomment-27273696) or update the post to the latest stable spec.

Contact: @umaar

**Comment by umaar** [comment]
I've gotten in touch with one of the editors to see if we can get a disclaimer added.

**Comment by umaar** [comment]
Update: A disclaimer has been added to the article.

**Comment by dstorey** [comment]
Thanks so much! Closed. Verified.
