### ISSUE TITLE
HTML5Rocks “Building an amazing fullscreen mobile experience” outdated syntax, etc.

### ISSUE THREAD

**Issue by dstorey** [dstorey/stale#3]
URL: http://www.html5rocks.com/en/mobile/fullscreen/

Issues:
- Examples shown without prefixes use the outdated syntax (`requestFullScreen` rather than `requestFullscreen` – capitalisation of the S)
- Code that shows the prefixes does not include the ms prefix for IE11+
- WebKit code uses old syntax (this could be updated or left as is, depending on how far back one wants to support)
- Uses old syntax for unprefixed CSS pseudo-class (should be `:fullscreen`) in `#goFS:full-screen #goFS` example. Note: IE11+ needs `:-ms-fullscreen` while WebKit still requires hyphen even though it supports the latest JS syntax)
- Doesn’t mention IE support in browser support info (obviously, as it was written prior to release)

Contact:

Github: @PaulKinlan (author)
Twitter: @Paul_Kinlan

**Comment by PaulKinlan** [comment]
Happy to take a patch if you want to take a stab at updating it.  Otherwise
it will be a while before I can get around to fixing it.

**Comment by dstorey** [comment]
@PaulKinlan I can try to look into that. What is the best way? Source is on GitHub or such?

**Comment by PaulKinlan** [comment]
I read this post thinking it was an issue on the repository.  The repository is on Github and you can get to the file in question here: https://github.com/html5rocks/www.html5rocks.com/blob/master/content/mobile/fullscreen/en/index.html

**Comment by dstorey** [comment]
@PaulKinlan created a pull request. Hopefully I did it right.

**Comment by PaulKinlan** [comment]
Awesome. Will check it out now.

**Comment by dstorey** [comment]
Resolved fixed.
