### ISSUE TITLE
Sitepoint “How to Use the HTML5 Full-Screen API” needs updating

### ISSUE THREAD

**Issue by dstorey** [dstorey/stale#4]
URL: http://www.sitepoint.com/html5-full-screen-api/

Issues:
- Uses old syntax. Should be lowercase S in `Fullscreen`, `exitFullscreen` rather than `cancelFullScreen`, and no hyphen in the CSS pseudo class `:fullscreen`
- Lacks ms prefix for IE11+. Note IE requires new syntax, FF requires old syntax, WebKit can use either, but still needs `:-webkit-full-screen` for CSS. MS prefix is shown later in article, but as the syntax changed it won't work. -o- prefix is also not needed.
- Browser support now out of date (for obvious reasons)

Contact:

GitHub & Twitter: @craigbuckler

**Comment by craigbuckler** [comment]
Thanks David - I'm on it.

**Comment by dstorey** [comment]
@craigbuckler thanks! BTW for some reason I typed that IE requires the old syntax in the report above. It doesn’t, it requires the new one (including for CSS)

**Comment by craigbuckler** [comment]
A new article should appear on SitePoint this week. The old article will have a link to the newer one.

Thanks for pointing out all the changes - can't believe there were so many in a year!

**Comment by dstorey** [comment]
Closing this as the new article was published. Thanks @craigbuckler !
