### ISSUE TITLE
HTML5Rocks “Jumping the hurdles” now outdated

### ISSUE THREAD

**Issue by dstorey** [dstorey/stale#45]
URL: http://www.html5rocks.com/en/tutorials/doodles/gamepad/

IE will be coming out with support for the Gamepad API. It won't work with the code samples and demos as:
- `getGamepads` method only uses `webkit` prefixes.
- Events only use `moz` prefixes
- Detection for support uses either `webkit` prefixes or browser sniffing for Firefox.
- Gamepad.buttons previously returned an array of doubles. In the latest spec (implemented by Firefox 29+ (28 behind a flag) and the upcoming version of IE) returns an array of GamepadButtons.

Support information is also out of date. Comments mention Firefox dropped the prefixes and needs to be enabled via a flag. FF29+ now ships with it enabled and prefixless now. Chrome also doesn't use WebKit prefix now.

MS have not announced which version of IE will ship with GamePad API. It will use the same spec version as FF29+, without prefixes.

Contact: @mwichary (author)

**Comment by PaulKinlan** [comment]
Can you file this on the h5r site and I will get someone to do it... i'll forget otherwise...

**Comment by dstorey** [comment]
Sure, thanks! Filed as https://github.com/html5rocks/www.html5rocks.com/issues/1081
