### ISSUE TITLE
Moz Wiki: GamePad API is out of date

### ISSUE THREAD

**Issue by dstorey** [dstorey/stale#47]
URL: https://wiki.mozilla.org/GamepadAPI
- Uses moz prefix for events. No longer uses prefixes in Firefox
- gamepad.buttons should be an array of objects rather than doubles (recent change in FF28)
- would be useful to include IE (when available) and Chrome info and any cross browser adaptations needed to the code samples

**Comment by luser** [comment]
I just cleaned out all that outdated content and put in links to the developer.mozilla.org docs and the hacks.mozilla.org post I did. That wiki was a development resource and I think it's outlived its usefulness.

**Comment by dstorey** [comment]
Thanks!
