### ISSUE TITLE
Dropshado.ws: WebKit Transform Perspective Function only uses webkit prefixes

### ISSUE THREAD

**Issue by dstorey** [dstorey/stale#56]
URL: http://dropshado.ws/post/1301087289/webkit-transform-perspective-function
Demo: http://jsfiddle.net/desandro/gU7X4/
Google positon: 1st, page 3

Issue:
- Only uses webkit prefixes, so doesn’t work unless you use webkit/blink

Fix:
- Add unprefixed versions

Contact: @desandro (Author)

**Comment by dstorey** [comment]
Applied fixes to http://jsfiddle.net/gU7X4/126/
- Added unprefixed versions
- unitless perspective values need a unit in the actual spec. Added px
- Updated text to show it works in all modern browsers
- Didn't add -moz- as it has been supported unprefixed for a while and it auto-updates these days

Should be able to replace the text of the blog post with the fiddle text.

**Comment by desandro** [comment]
Fixed!  http://dropshado.ws/post/1301087289/webkit-transform-perspective-function

Damn, this was an old one.

**Comment by dstorey** [comment]
Thanks for the quick turn around. Looks like you didn't add the units to the perspective values (should be `perspective(800px)`, but otherwise looks good!

**Comment by desandro** [comment]
ah, nice catch. That too

**Comment by dstorey** [comment]
Thanks!
