### ISSUE TITLE
PaulRHayes: “3D CSS Cube” only uses vendor prefixes

### ISSUE THREAD

**Issue by dstorey** [dstorey/stale#58]
URL: http://www.paulrhayes.com/2010-09/3d-css-cube-ii-touch-gestures-click-and-drag/
Linked from http://www.creativebloq.com/css3/20-stunning-examples-css-3d-transforms-11112759 (15th on Google for “CSS Transforms”)

Issues:
- Only moz and webkit prefixes are used in code samples and in demo. So doesn’t work in IE.

Fix:
- Add unprefixed versions of the properties (blog post and demo)

Code repo: https://github.com/fofr/paulrhayes.com-experiments/tree/master/cube-3d/

Contact: @fofr (author)

**Comment by dstorey** [comment]
Created a pull request for the demo https://github.com/fofr/paulrhayes.com-experiments/pull/11

Also needs pointer events to work correctly for touch in IE, but that is a separate bug.

**Comment by fofr** [comment]
Thanks :smile:

**Comment by dstorey** [comment]
Thanks!
